repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '2.2.1'
    hooks:
      - id: poetry-check
        name: poetry check backend
        args: ["-C", "packages/backend"]
      - id: poetry-lock
        name: poetry lock backend
        args: ["-C", "packages/backend"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        name: ruff check backend
        files: ^packages/backend/.*\.py$

      - id: ruff-format
        name: ruff format backend
        args: [--check]
        files: ^packages/backend/.*\.py$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: pyright
        name: pyright backend
        entry: pyright
        language: system
        types: [python]
        files: ^packages/backend/.*\.py$
        args: ["--project", "packages/backend"]
