name: Codestyle (Linting and Formatting)

# Yamllint falsely detects on as a truthy key:
# https://github.com/adrienverge/yamllint/issues/430
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "**"

env:
  DIRECTORY_BACKEND: packages/roboview

jobs:
  yamllint:
    name: Lint using Yamllint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install yamllint

      - name: Lint
        run: yamllint --config-file .yamllint.yaml .

  ruff:
    name: Lint using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install ruff
      - name: Lint
        run: ruff check --config .ruff.toml .
      - name: Format
        run: ruff format --config .ruff.toml --check

  pyright:
    name: Type check using Pyright for backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry and Dependencies
        uses: ./.github/workflows/poetry_template
        with:
          directory: ${{ env.DIRECTORY_BACKEND }}
          dev: "true"

      - name: Run Pyright
        run: |
          cd ${{ env.DIRECTORY_BACKEND }}
          poetry run pyright .
